package: responsemanagement_library
mainObject: Library
operations:
  - type: create
    method: POST
    path: /api/v2/responsemanagement/libraries
  - type: read
    method: GET
    path: /api/v2/responsemanagement/libraries/{libraryId}
  - type: update 
    method: PUT
    path: /api/v2/responsemanagement/libraries/{libraryId}
  - type: delete
    method: DELETE
    path: /api/v2/responsemanagement/libraries/{libraryId}
  - type: getAll
    method: GET
    path: /api/v2/responsemanagement/libraries
skeletonSchemaFile: true;
